import {
  View,
  Text,
  Image,
  FlatList,
  StyleSheet,
  StatusBar,
  Pressable,
  ScrollView,
} from "react-native";
import React, { useState, useRef, RefObject } from "react";
import { SafeAreaView } from "react-native-safe-area-context";
// import { Image } from "react-native-expo-image-cache";

const data = [
  {
    name: "\n1ª Estación: Jesús sentenciado a muerte",
    prayer:
//   "Te adoramos, Señor, y te bendecimos, porque por tu santa cruz redimiste al mundo. Sentenciado y no por un tribunal, sino por todos. Condenado por los mismos que le habían aclamado poco antes. Y El calla... Nosotros huímos de ser reprochados. Y saltamos inmediatamente... Dame, Señor, imitarte, uniéndome a Ti por el Silencio cuando alguien me haga sufrir. Yo lo merezco. ¡Ayúdame! Señor, pequé, ten piedad y misericordia de mí. Padre Nuestro, Ave María y Gloria...",
      "\nEl Sumo Sacerdote, poniéndose de pie ante la asamblea, interrogó a Jesús: «¿No respondes nada a lo que estos atestiguan contra ti?». El permanecía en silencio y no respondía nada. […] Pilato lo interrogó nuevamente: «¿No respondes nada? ¡Mira de todo lo que te acusan!». Pero Jesús ya no respondió a nada más, y esto dejó muy admirado a Pilato (Mc 14,60-61;15,4-5). \n\n Jesús, tú eres la vida, pero te condenan a muerte; eres la verdad y sin embargo eres víctima de un falso proceso. Pero, ¿por qué no te rebelas? ¿Por qué no levantas la voz y explicas cuáles son tus propias razones? ¿Por qué no rebates a los sabios y a los poderosos como siempre lo has hecho? Jesús, tu actitud desconcierta; en el momento decisivo no hablas, sino callas. Porque cuanto más fuerte es el mal, más radical es tu respuesta. Y tu respuesta es el silencio. Pero tu silencio es fecundo: es oración, es mansedumbre, es perdón, es la vía para redimir el mal, para convertir tus sufrimientos en un don que nos ofreces. Jesús, me doy cuenta de que apenas te conozco porque conozco poco tu silencio, porque en el frenesí de las prisas y del hacer, absorbido por las cosas, atrapado por el miedo de no mantenerme a flote o por el afán de querer ponerme siempre en el centro, no encuentro tiempo para detenerme y quedarme contigo; para permitirte a ti, Palabra del Padre, obrar en silencio. Jesús, tu silencio me estremece, me enseña que la oración no nace de los labios que se mueven, sino de un corazón que sabe escuchar. Porque rezar es hacerse dócil a tu Palabra, es adorar tu presencia. \n\nOremos diciendo: \nHáblame al corazón, Jesús \n\nTú que respondes al mal con el bien\nHáblame al corazón, Jesús \n\nTú que apagas los gritos con la mansedumbre\nHáblame al corazón, Jesús\n\nTú que detestas la murmuración y los reproches\nHáblame al corazón, Jesús\n\nTú que me conoces íntimamente\nHáblame al corazón, Jesús\n\nTú que me amas más de cuanto yo pueda amarme\nHáblame al corazón, Jesús.\n\nAutor:\nChrist Before Pilate (Muncasky)\n",
      image: require("@/assets/images/via_crucis/1ra-estacion.jpg"),
  },
  {
    name: "\n2ª Estación: Jesús cargado con la cruz",
    prayer:
//   "\nTe adoramos, Señor, y te bendecimos, porque por tu santa cruz redimiste al mundo. Que yo comprenda, Señor, el valor de la cruz, de mis pequeñas cruces de cada día, de mis achaques, de mis dolencias, de mi soledad. Dame convertir en ofrenda amorosa, en reparación por mi vida y en apostolado por mis hermanos, mi cruz de cada día. Señor, pequé, ten piedad y misericordia de mí. Padre Nuestro, Ave María y Gloria...",
      "\nÉl llevó sobre la cruz nuestros pecados,cargándolos en su cuerpo, a fin de que, muertos al pecado, vivamos para la justicia. Gracias a sus llagas, ustedes fueron curados(1 P 2,24).\n\nJesús, nosotros también cargamos nuestras cruces, a veces muy pesadas: una enfermedad, un accidente, la muerte de un ser querido, una decepción amorosa, un hijo que se perdió, la falta de trabajo, una herida interior que no cicatriza, el fracaso de un proyecto, una esperanza más que se malogra... Jesús, ¿cómo rezar ahí? ¿Cómo hacerlo cuando me siento aplastado por la vida, cuando un peso oprime mi corazón, cuando estoy bajo presión y ya no tengo fuerzas para reaccionar? Tu respuesta se encuentra en una invitación: «Vengan a mí todos los que están afligidos y agobiados, y yo los aliviaré» (Mt 11,28). Ir a ti; yo, en cambio, me encierro en mí mismo, rumiando mentalmente, escarbando en el pasado, quejándome, hundiéndome en el victimismo, paladín de negatividad. Vengan a mí; no te ha parecido suficiente decírnoslo, sino que has venido a nosotros para tomar nuestra cruz sobre tus hombros, y quitarnos su peso. Esto es lo que deseas: que descarguemos en ti nuestros cansancios y sinsabores, porque quieres que en ti nos sintamos libres y amados. Gracias, Jesús. Uno mi cruz a la tuya, te traigo mi fatiga y mis miserias, pongo en ti todo el agobio que tengo en mi corazón.\n\nOremos diciendo: \nAcudo a ti, Señor\n\nCon mi historia personal\nAcudo a ti, Señor\n\nCon mis cansancios\nAcudo a ti, Señor\n\nCon mis límites y mis fragilidades\nAcudo a ti, Señor\n\nCon mis miedos\nAcudo a ti, Señor\n\nConfiando sólo en tu amor\nAcudo a ti, Señor.\n\nAutor:\nChrist Carrying the Cross(El Greco, New York)\n",
      image: require("@/assets/images/via_crucis/2da-estacion.jpg"),
  },
  {
    name: "3ª Estación: Jesús cae, por primera vez, bajo el paso de la cruz",
    prayer:
      // "Te adoramos, Señor, y te bendecimos, porque por tu santa cruz redimiste al mundo. Tú caes, Señor, para redimirme. Para ayudarme a levantarme en mis caídas diarias, cuando después de haberme propuesto ser fiel, vuelvo a reincidir en mis defectos cotidianos. ¡Ayúdame a levantarme siempre y a seguir mi camino hacia Ti! Señor, pequé, ten piedad y misericordia de mí. Padre Nuestro, Ave María y Gloria...",
     "\nLes aseguro que si el grano de trigo que cae en la tierra no muere, queda solo; pero si muere, da mucho fruto (Jn 12,24).\n\nJesús, has caído. ¿En qué piensas?, ¿cómo rezas postrado rostro en tierra? Pero, sobre todo, ¿qué es lo que te da fuerzas para volver a levantarte? Mientras estás boca abajo en el suelo y ya no puedes ver el cielo, te imagino repitiendo en tu corazón: Padre, que estás en los cielos. La mirada amorosa del Padre posada en ti es tu fuerza. Pero imagino también que, mientras besas la tierra árida y fría, piensas en el hombre, sacado de la tierra, piensas en nosotros, que estamos en el centro de tu corazón; y que repites las palabras de tu testamento: «Esto es mi Cuerpo, que se entrega por ustedes» (Lc 22,19). El amor del Padre por ti y el tuyo por nosotros: el amor, ese es el estímulo que te hace levantarte y seguir adelante. Porque el que ama no se queda derrumbado, sino que vuelve a empezar; el que ama no se cansa, sino que corre; el que ama vuela. Jesús mío, siempre te pido muchas cosas, pero necesito sólo una: saber amar. Caeré en la vida, pero con amor podré volver a levantarme y seguir adelante, como hiciste tú, que tienes experiencia en las caídas. Tu vida, en efecto, ha sido una caída continua hacia nosotros: de Dios a hombre, de hombre a siervo, de siervo a crucificado, hasta el sepulcro; caíste en la tierra como semilla que muere, caíste para levantarnos de la tierra y llevarnos al cielo. Tú que levantas del polvo y reavivas la esperanza, dame la fuerza para amar y volver a empezar.\n\nOremos diciendo: \nJesús, dame la fuerza para amar y volver a empezar\n\nCuando prevalece la desilusión\nJesús, dame la fuerza para amar y volver a empezar\n\nCuando el juicio de los demás se abate sobre mí\nJesús, dame la fuerza para amar y volver a empezar\n\nCuando las cosas no van bien y me vuelvo intolerante\nJesús, dame la fuerza para amar y volver a empezar\n\nCuando siento que ya no puedo más\nJesús, dame la fuerza para amar y volver a empezar\n\nCuando me oprime el pensamiento de que nada cambiará\nJesús, dame la fuerza para amar y volver a empezar.\n\nAutor:\nChrist Carrying the Cross (Bosch)\n",
      image: require("@/assets/images/via_crucis/3ra-estacion.jpg"),
  },
  {
    name: "4ª Estación: Encuentro con la Virgen",
    prayer:
      // "Te adoramos, Señor, y te bendecimos, porque por tu santa cruz redimiste al mundo. Haz Señor, que me encuentre al lado de tu Madre en todos los momentos de mi vida. Con ella, apoyándome en su cariño maternal, tengo la seguridad de llegar a Ti en el último día de mi existencia. ¡Ayúdame Madre! Señor, pequé, ten piedad y misericordia de mí. Padre Nuestro, Ave María y Gloria....",
     "\nAl ver a la madre y cerca de ella al discípulo a quien él amaba, Jesús […] dijo al discípulo: «Aquí tienes a tu madre». Y desde aquel momento, el discípulo la recibió en su casa (Jn 19,26-27).\n\nJesús, los tuyos te han abandonado; Judas te ha traicionado, Pedro te ha negado. Te has quedado solo con la cruz, pero ahí está tu madre. No hacen falta palabras, son suficientes sus ojos que saben mirar de frente al sufrimiento y asumirlo. Jesús, en la mirada de María, llena de lágrimas y de luz, encuentras el grato recuerdo de su ternura, de sus caricias, de sus brazos amorosos que siempre te han acogido y sostenido. La mirada de la propia madre es la mirada de la memoria, que nos cimienta en el bien. No podemos prescindir de una madre que nos dé a luz, pero tampoco de una madre que nos encarrile en el mundo. Tú lo sabes y desde la cruz nos entregas a tu propia madre. Aquí tienes a tu madre, dices al discípulo, a cada uno de nosotros. Después de la Eucaristía, nos das a María, tu último don antes de morir. Jesús, tu camino fue consolado por el recuerdo de su amor; también mi camino necesita cimentarse en la memoria del bien. Sin embargo, me doy cuenta de que mi oración es pobre en memoria: es rápida, apresurada; con una lista de necesidades para hoy y mañana. María, detén mi carrera, ayúdame a hacer memoria: a custodiar la gracia, a recordar el perdón y las maravillas de Dios, a reavivar el primer amor, a saborear de nuevo las maravillas de la providencia, a llorar de gratitud.\n\nOremos diciendo: Reaviva en mí, Señor, el recuerdo de tu amor\n\nCuando vuelven a aparecer las heridas del pasado\nReaviva en mí, Señor, el recuerdo de tu amor\n\nCuando pierdo el sentido y el rumbo de las cosas\nReaviva en mí, Señor, el recuerdo de tu amor\n\nCuando pierdo de vista los dones que he recibido\nReaviva en mí, Señor, el recuerdo de tu amor\n\nCuando pierdo de vista el don de mi propio ser\nReaviva en mí, Señor, el recuerdo de tu amor\n\nCuando me olvido de agradecerte\nReaviva en mí, Señor, el recuerdo de tu amor.\n\nAutor:\nChrist Meeting his Mother on the Way to Calvary (di Bartolo)\n",
    image: require("@/assets/images/via_crucis/4ta-estacion.jpg"),
  },
  {
    name: "5ª Estación: el Cirineo ayuda al Señor a llevar la Cruz",
    prayer:
      // "Te adoramos, Señor, y te bendecimos, porque por tu santa cruz redimiste al mundo. Cada uno de nosotros tenemos nuestra vocación, hemos venido al mundo para algo concreto, para realizarnos de una manera particular. ¿Cuál es la mía y cómo la llevo a cabo? Pero hay algo, Señor, que es misión mía y de todos: la de ser Cirineo de los demás, la de ayudar a todos. ¿Cómo llevo adelante la realización de mi misión de Cirineo? Señor, pequé, ten piedad y misericordia de mí. Padre Nuestro, Ave María y Gloria...",
     "\nCuando [los soldados] lo llevaban, detuvieron a un tal Simón de Cirene, que volvía del campo, y lo cargaron con la cruz, para que la llevara detrás de Jesús (Lc 23,26).\n\nJesús, cuántas veces, frente a los retos de la vida, presumimos de lograr hacer todo sólo con nuestras propias fuerzas. ¡Qué difícil nos resulta pedir ayuda, ya sea por miedo a dar la impresión de que no estamos a la altura de las circunstancias, o porque siempre nos preocupamos por quedar bien y lucirnos! No es fácil confiar, y menos aún abandonarse. En cambio, quien reza es porque está necesitado, y tú, Jesús, estás acostumbrado a abandonarte en la oración. Por eso no desdeñas la ayuda del Cirineo. Le muestras tus fragilidades a un hombre sencillo, a un campesino que vuelve del campo. Gracias porque, al dejarte ayudar en tu necesidad, borras la imagen de un dios invulnerable y lejano. Tú no te muestras imbatible en el poder, sino invencible en el amor, y nos enseñas que amar significa socorrer a los demás precisamente allí, en las debilidades de las que se avergüenzan. De este modo, las fragilidades se transforman en oportunidades. Fue lo que le sucedió a Cirineo: tu debilidad cambió su vida y un día se daría cuenta de que había ayudado a su Salvador, de que había sido redimido por medio de esa cruz que cargó. Para que mi vida también cambie, te ruego, Jesús: ayúdame a bajar mis defensas y a dejarme amar por ti; justo ahí, donde más me avergüenzo de mí mismo.\n\nOremos diciendo: Sáname, Jesús\n\nDe toda presunción de autosuficiencia\nSáname, Jesús\n\nDe creer que puedo prescindir de ti y de los demás\nSáname, Jesús\n\nDel afán de perfeccionismo\nSáname, Jesús\n\nDe la reticencia a entregarte mis miserias\nSáname, Jesús\n\nDe la prisa mostrada ante los necesitados que encuentro en mi camino\nSáname, Jesús\n\nAutor:\nChrist Carrying the Cross (Titian)\n",
    image: require("@/assets/images/via_crucis/5ta-estacion.jpg"),
  },
  {
    name: "6ª Estación: la Verónica enjuga el rostro de Jesús",
    prayer:
      // 'Te adoramos, Señor, y te bendecimos, porque por tu santa cruz redimiste al mundo. Es la mujer valiente, decidida, que se acerca a Ti cuando todos te abandonan. Yo, Señor, te abandono cuando me dejo llevar por el "qúe dirán", del respeto humano, cuando no me atrevo a defender al prójimo ausente, cuando no me atrevo a replicar una broma que ridiculiza a los que tratan de acercarse a Ti. Y en tantas otras ocasiones. Ayúdame a no dejarme llevar por el respeto humano, por el "qué dirán". Señor, pequé, ten piedad y misericordia de mí. Padre Nuestro, Ave María y Gloria...',
     "\nBendito sea Dios […] Padre de las misericordias y Dios de todo consuelo, que nos reconforta en todas nuestras tribulaciones, para que nosotros podamos dar a los que sufren el mismo consuelo […]. Porque así como participamos abundantemente de los sufrimientos de Cristo, también por medio de Cristo abunda nuestro consuelo (2 Co 1,3-5).\n\nJesús, son tantos los que asisten al bárbaro espectáculo de tu ejecución y, sin conocerte y sin saber la verdad, emiten juicios y condenas, arrojando sobre ti infamia y desprecio. Sucede también hoy, Señor, y ni siquiera es necesario un cortejo macabro; basta un teclado para insultar y publicar condenas. Pero mientras tantos gritan y juzgan, una mujer se abre paso entre la multitud. No habla, actúa. No protesta, se compadece. Va contra la corriente, sola, con la valentía de la compasión; se arriesga por amor, encuentra la manera de pasar entre los soldados sólo para brindarte el consuelo de una caricia en el rostro. Su gesto pasará a la historia y como un gesto de consuelo. ¡Cuántas veces habré invocado tu consuelo, Jesús! Y ahora la Verónica me recuerda que tú también lo necesitas. Tú, Dios cercano, pides mi cercanía; tú, consolador mío, quieres ser consolado por mí. Amor no amado, buscas aún hoy entre la multitud corazones sensibles a tu sufrimiento, a tu dolor. Buscas verdaderos adoradores, que en espíritu y en verdad (cf. Jn 4,23) permanezcan contigo (cf. Jn 15), Amor abandonado. Jesús, enciende en mí el deseo de estar contigo, de adorarte y consolarte. Y haz que yo, en tu nombre, sea consuelo para los demás.\n\nOremos diciendo: Hazme testigo de tu consuelo\n\nDios de misericordia, que te haces cercano a quien tiene el corazón herido\nHazme testigo de tu consuelo\n\nDios de ternura, que te conmueves por nosotros\nHazme testigo de tu consuelo\n\nDios de compasión, que detestas la indiferencia\nHazme testigo de tu consuelo\n\nTú, que te entristeces cuando señalo con el dedo a los demás\nHazme testigo de tu consuelo\n\nTú, que no has venido a condenar sino a salvar\nHazme testigo de tu consuelo\n\nAutor:\nSaint Veronica (Memling)\n",
    image: require("@/assets/images/via_crucis/6ta-estacion.jpg"),
  },
  {
    name: "7ª Estación: Segunda caída en el camino de la Cruz",
    prayer:
      // "Te adoramos, Señor, y te bendecimos, porque por tu santa cruz redimiste al mundo. Caes, Señor, por segunda vez. El Via Crucis nos señala tres caídas en tu caminar hacia el Calvario. Tal vez fueran más. Caes delante de todos... ¿Cuándo aprenderé yo a no temer el quedar mál ante los demás, por un error, por una equivocación?. ¿Cuándo aprenderé que también eso se puede convertir en ofrenda? Señor, pequé, ten piedad y misericordia de mí. Padre Nuestro, Ave María y Gloria...",
     "\n[El hijo menor] recapacitó y dijo: Ahora mismo iré a la casa de mi padre y le diré: «Padre, pequé» […]. Entonces partió y volvió a la casa de su padre. Cuando todavía estaba lejos, su padre lo vio y se conmovió profundamente, corrió a su encuentro, lo abrazó y lo besó. El joven le dijo: «Padre, pequé […]; no merezco ser llamado hijo tuyo». Pero el padre dijo: […] «mi hijo estaba muerto y ha vuelto a la vida, estaba perdido y fue encontrado»(Lc 15,17-18.20-22.24).\n\nJesús, la cruz pesa mucho; lleva en sí el peso de la derrota, del fracaso, de la humillación. Lo comprendo cuando me siento aplastado por las cosas, acosado por la vida e incomprendido por los demás; cuando siento el peso excesivo y exasperante de la responsabilidad y del trabajo, cuando me siento oprimido en las garras de la ansiedad, asaltado por la melancolía, mientras un pensamiento asfixiante me repite: no saldrás adelante, esta vez no te levantarás. Pero las cosas empeoran aún más. Me doy cuenta de que toco fondo cuando vuelvo a caer, cuando recaigo en mis errores, en mis pecados, cuando me escandalizo de los demás y luego me doy cuenta de que yo no soy distinto de ellos. No hay nada peor que sentirse decepcionado de sí mismo, aplastado por los sentimientos de culpa. Pero tú, Jesús, caíste muchas veces bajo el peso de la cruz para estar a mi lado cuando yo caigo. Contigo la esperanza nunca se acaba, y después de cada caída nos volvemos a levantar, porque cuando me equivoco no te cansas de mí, sino que te acercas más a mí. Gracias porque me esperas; gracias, pues, aunque caiga muchas veces me perdonas siempre, siempre. Recuérdame que las caídas se pueden convertir en momentos cruciales del camino, porque me llevan a comprender que lo único que importa es que te necesito. Jesús, imprime en mi corazón la certeza más importante: que vuelvo a levantarme de verdad sólo cuando me levantas tú, cuando me liberas del pecado. Porque la vida no vuelve a empezar con mis palabras, sino con tu perdón.\n\nOremos diciendo: Levántame, Jesús\n\nCuando, paralizado por la desconfianza, siento tristeza y desesperación\nLevántame, Jesús\n\nCuando veo mi incapacidad y me siento inútil\nLevántame, Jesús\n\nCuando prevalecen la vergüenza y el miedo al fracaso\nLevántame, Jesús\n\nCuando tengo la tentación de perder la esperanza\nLevántame, Jesús\n\nCuando olvido que mi fortaleza está en tu perdón\nLevántame, Jesús\n\nAutor:\nChrist Falling on the Way to Calvary (Domenico Tiepolo)",
    image: require("@/assets/images/via_crucis/7ma-estacion.jpg"),
  },
  {
    name: "8ª Estación: Jesús consuela a las hijas de Jerusalén",
    prayer:
      // "Te adoramos, Señor, y te bendecimos, porque por tu santa cruz redimiste al mundo. Muchas veces, tendría yo que analizar la causa de mis lágrimas. Al menos, de mis pesares, de mis preocupaciones. Tal vez hay en ellos un fondo de orgullo, de amor propio mal entendido, de egoismo, de envidia. Debería llorar por mi falta de correspondencia a tus innumerables beneficios de cada día, que me manifiestan, Señor, cuánto me quieres. Dame profunda gratitud y correspondencia a tu misericordia. Señor, pequé, ten piedad y misericordia de mí. Padre Nuestro, Ave María y Gloria...",
     "\nLo seguían muchos del pueblo y un buen número de mujeres, que se golpeaban el pecho y se lamentaban por él (Lc 23,27).\n\nJesús, ¿quién te acompaña hasta el final en tu camino de la cruz? No son los poderosos, que te esperan en el Calvario, ni los espectadores que se quedan lejos, sino la gente sencilla, grande a tus ojos, pero pequeña a los del mundo. Son esas mujeres, a las que has dado esperanza; que no tienen voz, pero se hacen oír. Ayúdanos a reconocer la grandeza de las mujeres, las que en Pascua te fueron fieles y no te abandonaron, las que aún hoy siguen siendo descartadas, sufriendo ultrajes y violencia. Jesús, las mujeres que encuentras se golpean el pecho y se lamentan por ti. No lloran por ellas, sino que lloran por ti, lloran por el mal y el pecado del mundo. Su oración hecha de lágrimas llega a tu corazón. ¿Acaso mi oración sabe llorar? ¿Me conmuevo ante ti, crucificado por mí, ante tu amor bondadoso y herido? ¿Lloro por mis falsedades y mi inconstancia? Ante las tragedias del mundo, ¿mi corazón permanece frío o se conmueve? ¿Cómo reacciono ante la locura de la guerra, ante los rostros de los niños que ya no saben sonreír, ante sus madres que los ven desnutridos y hambrientos sin tener siquiera más lágrimas que derramar? Tú, Jesús, has llorado por Jerusalén, has llorado por la dureza de nuestros corazones. Sacúdeme por dentro, dame la gracia de llorar rezando y de rezar llorando.\n\nOremos diciendo: Jesús, ablanda mi corazón endurecido\n\nTú que conoces los secretos del corazón\nJesús, ablanda mi corazón endurecido\n\nTú que te entristeces ante la dureza de los ánimos\nJesús, ablanda mi corazón endurecido\n\nTú que amas los corazones contritos y humillados\nJesús, ablanda mi corazón endurecido\n\nTú que enjugaste con el perdón las lágrimas de Pedro\nJesús, ablanda mi corazón endurecido\n\nTú que transformas el llanto en canto\nJesús, ablanda mi corazón endurecido\n\nAutor:\nChrist Falling on the Way to Calvary (Raphael)\n",
    image: require("@/assets/images/via_crucis/8va-estacion.jpg"),
  },
  {
    name: "9ª Estación: Jesús cae por tercera vez",
    prayer:
      // "Te adoramos, Señor, y te bendecimos, porque por tu santa cruz redimiste al mundo. Tercera caída. Más cerca de la Cruz. Más agotado, más falto de fuerzas. Caes desfallecido, Señor. Yo digo que me pesan los años, que no soy el de antes, que me siento incapaz. Dame, Señor, imitarte en esta tercera caída y haz que mi desfallecimiento sea beneficioso para otros, porque te lo doy a Ti para ellos. Señor, pequé, ten piedad y misericordia de mí. Padre Nuestro, Ave María y Gloria...",
     "\n«Señor, ¿cuándo te vimos hambriento, y te dimos de comer; sediento y te dimos de beber? ¿Cuándo te vimos de paso, y te alojamos; desnudo y te vestimos? ¿Cuándo te vimos enfermo o preso, y fuimos a verte?» […]. Les responderá: «Les aseguro que cada vez que lo hicieron con el más pequeño de mis hermanos, lo hicieron conmigo» (Mt 25,37-40).\n\nJesús, estas son las palabras que dijiste antes de la Pasión. Ahora comprendo esa insistencia tuya en identificarte con los necesitados: tú, encarcelado; tú, extranjero, conducido fuera de la ciudad para ser crucificado; tú, desnudo, despojado de tus vestidos; tú, enfermo y herido; tú, sediento en la cruz y hambriento de amor. Concédeme que pueda verte en los que sufren y que a los que sufren los pueda ver en ti, porque tú estás ahí, en quien está despojado de dignidad, en los cristos humillados por la prepotencia y la injusticia, por las ganancias injustas obtenidas a costa de los demás y ante la indiferencia general. Te miro, Jesús, despojado de tus vestiduras, y comprendo que me invitas a despojarme de tantas exterioridades vacías. Porque tú no miras las apariencias, sino el corazón. Y no quieres una oración estéril, sino fecunda en caridad. Dios despojado, ponme al descubierto también a mí. Porque es fácil hablar, pero luego, ¿te amo yo de verdad en los pobres, en tu carne herida? ¿Rezo por los que han sido despojados de dignidad? ¿O rezo sólo para cubrir mis propias necesidades y revestirme de seguridad? Jesús, tu verdad me deja al descubierto y me lleva a ocuparme de lo que importa: tú crucificado, y los hermanos crucificados. Concédeme que lo comprenda ahora, para que no me encuentre falto de amor cuando deba presentarme ante ti.\n\nOremos diciendo: Despójame, Señor Jesús\n\nDel apego a las apariencias\nDespójame, Señor Jesús\n\nDe la armadura de la indiferencia\nDespójame, Señor Jesús\n\nDel creer que yo no tenga que socorrer a los demás\nDespójame, Señor Jesús\n\nDe un culto hecho de convencionalismo y exterioridad\nDespójame, Señor Jesús\n\nDe la convicción de que en la vida todo está bienbsi yo estoy bien\nDespójame, Señor Jesús\n\nAutor:\nChrist Carrying the Cross (Battista Tiepolo)",
    image: require("@/assets/images/via_crucis/9na-estacion.jpg"),
  },
  {
    name: "10ª Estación: Jesús despojado de sus vestiduras",
    prayer:
      // "Te adoramos, Señor, y te bendecimos, porque por tu santa cruz redimiste al mundo. Arrancan tus vestiduras, adheridas a Ti por la sangre de tus heridas. A infinita distancia de tu dolor, yo he sentido, a veces, cómo algo se arrancaba dolorosamente de mí por la pérdida de mis seres queridos. Que yo sepa ofrecerte el recuerdo de las separaciones que me desgarraron, uniéndome a tu pasión y esforzándome en consolar a los que sufren, huyendo de mi propio egoismo. Señor, pequé, ten piedad y misericordia de mí. Padre Nuestro, Ave María y Gloria...",
     "\nCuando llegaron al lugar llamado «del Cráneo», lo crucificaron junto con los malhechores, uno a su derecha y el otro a su izquierda. Jesús decía: «Padre, perdónalos, porque no saben lo que hacen» (Lc 23,33-34).\n\nJesús, te perforan las manos y los pies con clavos, lacerando tu carne, y justo ahora, mientras el dolor físico se hace más insoportable, brota de tus labios la oración imposible, perdonas al que te está hundiendo los clavos en las muñecas. Y no sólo una vez, sino muchas veces, como recuerda el Evangelio, con ese verbo que indica una acción repetida, decías 'Padre, perdona'. Por eso, contigo, Jesús, también yo puedo encontrar el valor de elegir el perdón que libera el corazón y relanza la vida. Señor, no te basta con perdonarnos, sino también nos justificas ante el Padre: no saben lo que hacen. Toma nuestra defensa, hazte nuestro abogado, intercede por nosotros. Ahora que tus manos, con las que bendecías y curabas, están clavadas, y tus pies, con los que traías la buena nueva, ya no pueden caminar, ahora, en la impotencia, nos revelas la omnipotencia de la oración. En la cumbre del Gólgota nos revelas la altura de la oración de intercesión que salva al mundo. Jesús, que yo no rece sólo por mí y por mis seres queridos, sino también por los que no me quieren y me hacen daño; que yo rece según los deseos de tu corazón, por los que están lejos de ti; reparando e intercediendo en favor de los que, ignorándote, no conocen la alegría de amarte y de ser perdonados por ti.\n\nOremos diciendo: Padre, ten misericordia de nosotros y del mundo entero\n\nPor la dolorosa pasión de Jesús\nPadre, ten misericordia de nosotros y del mundo entero\n\nPor el poder de sus llagas\nPadre, ten misericordia de nosotros y del mundo entero\n\nPor su perdón en la cruz\nPadre, ten misericordia de nosotros y del mundo entero\n\nPor cuantos perdonan por amor a ti\nPadre, ten misericordia de nosotros y del mundo entero\n\nPor la intercesión de los que creen, adoran, esperan y te aman\nPadre, ten misericordia de nosotros y del mundo entero\n\nAutor:\nJesus Insulted by the Soldiers (Manet)\n",
    image: require("@/assets/images/via_crucis/10ma-estacion.jpg"),
  },
  {
    name: "11ª Estación: Jesús es clavado en la Cruz",
    prayer:
      // "Te adoramos, Señor, y te bendecimos, porque por tu Santa Cruz redimiste al mundo. Señor, que yo disminuya mis limitaciones con mi esfuerzo y así pueda ayudar a mis hermanos. Y que cuando mi esfuerzo no consiga disminuirlas, me esfuerce en ofrecértelas también por ellos. Señor, pequé, ten piedad y misericordia de mí. Padre Nuestro, Ave María y Gloria...",
    "\nDesde el mediodía hasta las tres de la tarde, las tinieblas cubrieron toda la región. Hacia las tres de la tarde, Jesús exclamó en alta voz: «Elí, Elí, lemá sabactani», que significa: «Dios mío, Dios mío, ¿por qué me has abandonado?» (Mt 27,45-46).\n\nJesús, he aquí una oración sin precedentes: clamas al Padre tu abandono. Tú, Dios del cielo, que no replicas estruendosamente ninguna respuesta, sino que preguntas ¿por qué? En el ápice de la Pasión experimentas el alejamiento del Padre y ya ni siquiera le llamas Padre, como haces siempre, sino Dios, como si fueras incapaz de identificar su rostro. ¿Por qué? Para sumergirte hasta el fondo del abismo de nuestro dolor. Tú lo hiciste por mí, para que cuando sólo vea tinieblas, cuando experimente el derrumbamiento de las certezas y el naufragio del vivir, ya no me sienta solo, sino que crea que tú estás ahí conmigo; tú, Dios de la comunión, experimentaste el abandono para no dejarme más como rehén de la soledad. Cuando gritaste tu por qué, lo hiciste con un salmo; así convertiste en oración incluso la desolación más extrema. Esto es lo que hay que hacer en las tormentas de la vida; en vez de callar y aguantar, clamar a ti. Gloria a ti, Señor Jesús, porque no has huido de mi desolación, sino que la has habitado hasta lo más profundo. Alabanza y gloria a ti que, cargando sobre ti toda lejanía, te has hecho cercano a los más alejados de ti. Y yo, en las tinieblas de mis porqués, te encuentro a ti, Jesús, luz en la noche. Y en el grito de tantas personas solas y excluidas, oprimidas y abandonadas, te veo a ti, Dios mío: haz que te reconozca y te ame.\n\nOremos diciendo: Haz, Jesús, que te reconozca y te ame\n\nEn los niños no nacidos y en aquellos abandonados\nHaz, Jesús, que te reconozca y te ame\n\nEn tantos jóvenes, en espera de que alguien oiga su grito de dolor\nHaz, Jesús, que te reconozca y te ame\n\nEn los numerosos ancianos descartados\nHaz, Jesús, que te reconozca y te ame\n\nEn los prisioneros y en quien se encuentra solo\nHaz, Jesús, que te reconozca y te ame\n\nEn los pueblos más explotados y olvidados\nHaz, Jesús, que te reconozca y te ame\n\nAutor:\nChrist Nailed to the Cross (Fra Angelico)\n",
    image: require("@/assets/images/via_crucis/11ma-estacion.jpg"),
  },
  {
    name: "12ª Estación: Jesús muere en la Cruz",
    prayer:
      // "Te adoramos, Señor, y te bendecimos, porque por tu santa cruz redimiste al mundo. Te adoro, mi Señor, muerto en la Cruz por Salvarme. Te adoro y beso tus llagas, las heridas de los clavos, la lanzada del costado... ¡Gracias, Señor, gracias! Has muerto por salvarme, por salvarnos. Dame responder a tu amor con amor, cumplir tu Voluntad, trabajar por mi salvación, ayudado de tu gracia. Y dame trabajar con ahínco por la salvación de mis hermanos. Señor, pequé, ten piedad y misericordia de mí. Padre Nuestro, Ave María y Gloria...",
     "\n[Uno de los malhechores crucificados] decía: «Jesús, acuérdate de mí cuando vengas a establecer tu Reino». Él le respondió: «Yo te aseguro que hoy estarás conmigo en el Paraíso» […]. Jesús, con un grito, exclamó: «Padre, en tus manos encomiendo mi espíritu». Y diciendo esto, expiró(Lc 23,42-43.46).\n\nJesús, ¡un malhechor va al Paraíso! Él se encomienda a ti y tú lo encomiendas contigo al Padre. Dios de lo imposible, que haces santo a un ladrón. Y no sólo eso: en el Calvario cambias el curso de la historia. Conviertes la cruz, que es emblema del tormento, en icono del amor; cambias el muro de la muerte en puente hacia la vida. Transformas la oscuridad en luz, la separación en comunión, el dolor en danza e incluso el sepulcro ―última estación de la vida― en punto de partida de la esperanza. Pero estas transformaciones las realizas con nosotros, nunca sin nosotros. Jesús, acuérdate de mí: esta oración sincera te permitió obrar maravillas en la vida de aquel malhechor. Qué poder inaudito el de la oración. A veces pienso que mi oración no es escuchada, mientras que lo esencial es perseverar, tener constancia, acordarme de decirte: “Jesús, acuérdate de mí”. Acuérdate de mí y mi mal ya no será un final, sino un nuevo inicio. Acuérdate, vuelve a ponerme en tu corazón, incluso cuando me aleje, cuando me pierda en la rueda de la vida que gira vertiginosamente. Acuérdate de mí, Jesús, porque ser recordado por ti ―lo demuestra el buen ladrón― es entrar en el Paraíso. Sobre todo, recuérdame, Jesús, que mi oración puede cambiar la historia.\n\nOremos diciendo: Jesús, acuérdate de mí\n\nCuando la esperanza desaparece y reina la desilusión\nJesús, acuérdate de mí\n\nCuando no soy capaz de tomar una decisión\nJesús, acuérdate de mí\n\nCuando pierdo la confianza en mí o en los demás\nJesús, acuérdate de mí\n\nCuando pierdo de vista la grandeza de tu amor\nJesús, acuérdate de mí\n\nCuando creo que mi oración resulta inútil\nJesús, acuérdate de mí\n\nAutor:\nChrist Crucified (Velazquez)\n",
    image: require("@/assets/images/via_crucis/12va-estacion.jpg"),
  },
  {
    name: "13ª Estación: Jesús en brazos de su madre",
    prayer:
      // "Te adoramos, Señor, y te bendecimos, porque por tu santa cruz redimiste al mundo. Déjame estar a tu lado, Madre, especialmente en estos momentos de tu dolor incomparable. Déjame estar a tu lado. Más te pido: que hoy y siempre me tengas cerca de Ti y te compadezcas de mí. ¡Mírame con compasión , no me dejes, Madre mía! Señor, pequé, ten piedad y misericordia de mí. Amén. Padre Nuestro, Ave María y Gloria...",
     "\nSimeón […] dijo a María, la madre: «Este niño será causa de caída y de elevación para muchos en Israel; será signo de contradicción, y a ti misma una espada te atravesará el corazón» (Lc 2,33-35).\n\nMaría, después de tu 'sí' el Verbo se hizo carne en tu seno; ahora yace en tu regazo su carne torturada. Aquel niño que tuviste en tus brazos ahora es un cadáver destrozado. Sin embargo, ahora, en el momento más doloroso, resplandece la ofrenda de ti misma: una espada atraviesa tu alma y tu oración sigue siendo un 'sí' a Dios. María, nosotros somos pobres de 'síes', pero ricos del 'si': si yo hubiera tenido mejores padres, si me hubieran comprendido y amado más, si mi carrera hubiera ido mejor, si no hubiera tenido aquel problema, si tan sólo no sufriera más, si Dios me escuchara... Preguntándonos siempre el porqué de las cosas, nos cuesta vivir el presente con amor. Tú tendrías tantos 'si' que decirle a Dios, en cambio, sigues diciendo 'sí', se cumpla en mí. Fuerte en la fe, crees que el dolor, atravesado por el amor, da frutos de salvación; que el sufrimiento acompañado por Dios no tiene la última palabra. Y mientras sostienes en tus brazos a Jesús sin vida, resuenan en ti las últimas palabras que te dirigió: He aquí a tu hijo. Madre, ¡yo soy ese hijo! Recíbeme en tus brazos e inclínate sobre mis heridas. Ayúdame a decirle 'sí' a Dios, 'sí' al amor. Madre de misericordia, vivimos en un tiempo despiadado y necesitamos compasión: tú, tierna y fuerte, úngenos con mansedumbre; deshaz las resistencias del corazón y los nudos del alma\n\nOremos diciendo: Tómame de la mano, María\n\nCuando cedo a la recriminación y al victimismo\nTómame de la mano, María\n\nCuando dejo de luchar y acepto convivir con mis falsedades\nTómame de la mano, María\n\nCuando titubeo y non tengo el valor de decirle “sí” a Dios\nTómame de la mano, María\n\nCuando soy indulgente conmigo mismo e inflexible con los demás\nTómame de la mano, María\n\nCuando quiero que la Iglesia y el mundo cambien, pero yo no cambio\nTómame de la mano, María\n\nAutor:\nThe Descent from the Cross(van der Weyden)\n",
    image: require("@/assets/images/via_crucis/13ma-estacion.jpg"),
  },
  {
    name: "14ª Estación: Jesús en brazos de su madre",
    prayer:
      // "Te adoramos, Señor, y te bendecimos, porque por tu santa cruz redimiste al mundo. Déjame estar a tu lado, Madre, especialmente en estos momentos de tu dolor incomparable. Déjame estar a tu lado. Más te pido: que hoy y siempre me tengas cerca de Ti y te compadezcas de mí. ¡Mírame con compasión , no me dejes, Madre mía! Señor, pequé, ten piedad y misericordia de mí. Amén. Padre Nuestro, Ave María y Gloria...",
     "\nAl atardecer, llegó un hombre rico de Arimatea, llamado José, que también se había hecho discípulo de Jesús, y fue a ver a Pilato para pedirle el cuerpo de Jesús. […] José tomó el cuerpo, lo envolvió en una sábana limpia y lo depositó en un sepulcro nuevo que se había hecho cavar en la roca (Mt 27,57-60).\n\nJosé, ese es el nombre que, junto con el de María, marcan la aurora de la Navidad y marcan también la aurora de la Pascua. José de Nazaret advertido en sueños se llevó audazmente a Jesús para salvarlo de Herodes; tú, José de Arimatea, te llevas su cuerpo, sin saber que un sueño imposible y maravilloso se hará realidad allí mismo, en el sepulcro que le diste a Cristo cuando pensabas que él ya no podía hacer nada más por ti. En cambio, es verdad que todo don hecho a Dios es recompensado siempre por él. José de Arimatea, eres el profeta del valor intrépido. Para entregarle tu regalo a un muerto acudes al temido Pilato y le ruegas que te permita darle a Jesús la tumba que habías mandado a construir para ti. Tu oración es persistente y a las palabras siguen los hechos. José, recuérdanos que la oración perseverante da fruto y atraviesa incluso las tinieblas de la muerte; que el amor no se queda sin respuesta, sino que regala nuevos comienzos. Tu sepulcro, que ―único en la historia― será fuente de vida, era nuevo, recién labrado en la roca. Y yo, ¿qué cosa nueva le doy a Jesús en esta Pascua? ¿Un poco de tiempo para estar con Él? ¿Un poco de amor a los demás? ¿Mis miedos y miserias enterradas, que Cristo está esperando que le ofrezca, como tú, José, hiciste con el sepulcro? Será verdaderamente Pascua si doy algo de lo mío a Aquel que dio la vida por mí; porque es dando como se recibe; y porque la vida se encuentra cuando se pierde y se posee cuando se da.\n\nOremos diciendo: Señor, ten piedad\n\nDe mí, negligente para convertirme\nSeñor, te piedad\n\nDe mí, que me gusta recibir mucho, pero dar poco\nSeñor, te piedad\n\nDe mí, incapaz de rendirme a tu amor\nSeñor, te piedad\n\nDe nosotros, rápidos para servirnos de las cosas, pero lentos para el servicio a los demás\nSeñor, te piedad\n\nDe nuestro mundo, plagado de los sepulcros de nuestro egoísmo\nSeñor, te piedad\n\nAutor:\nThe Entombment of Christ(Caravaggio)\n",
    image: require("@/assets/images/via_crucis/14ta-estacion.jpg"),
  },
];

export default function ViaCrucis() {
  const [indexNum, setIndexNum] = useState(1);
  const listRef = useRef<FlatList | null>(null);

  const handlePrev = (listRef: RefObject<FlatList>) => {
    if (listRef.current) {
      listRef.current.scrollToIndex({ index: indexNum });
      setIndexNum(indexNum - 1);
    }
  };

  const handleNext = (listRef: RefObject<FlatList>) => {
    if (listRef.current) {
      listRef.current.scrollToIndex({ index: indexNum });
      setIndexNum(indexNum + 1);
    }
  };

  return (
    <ScrollView style={styles.container}>
    <FlatList
      ref={listRef}
      horizontal={true}
      data={data}
      keyExtractor={(item, index) => index.toString()}
      renderItem={({ item }) => (
        <View style={styles.itemContainer}>
          <Image
            style={styles.image}
            source={item.image}
          />
          <ScrollView style={styles.textContainer}>
            <Text style={styles.title}>{item.name}</Text>
            <Text style={styles.prayer}>{item.prayer}</Text>
          </ScrollView>
        </View>
      )}
    />
  </ScrollView>
);
}

const styles = StyleSheet.create({
container: {
  flex: 1,
},
itemContainer: {
  width: 350,
  height: 580,
  marginTop: 60,
  marginRight: 10,
},
image: {
  width: 300,
  height: 290,
  resizeMode: "cover",
  borderTopLeftRadius: 10,
  borderTopRightRadius: 10,
},
textContainer: {
  backgroundColor: "white",
  padding: 4,
  flexGrow: 1,
  borderBottomEndRadius: 10,
  borderBottomLeftRadius: 10,
},
title: {
  fontWeight: "bold",
  fontSize: 18,
  color: "black",
  fontFamily: 'sans-serif',
},
prayer: {
  fontSize: 16,
  color: "black",
  fontFamily: 'sans-serif',
},
});